import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { getGlobalPageData } from "@/data/loaders";
import { Header } from "@/components/customs/Header";
import { Footer } from "@/components/customs/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalPageData();
  console.dir(globalData, { depth: null });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={globalData.header} />
        <div>{children}</div>
        <Footer data={globalData.footer} />
      </body>
    </html>
  );
}
